config/routes.rb
Asto::Application.routes.draw do

  get "users/signup_completed"

  get "superbowl/confirm"
  get "superbowl/home"
  match "/approve/:id" => "superbowl#approve"
  match "/disapprove/:id" => "superbowl#disapprove"
  match "/confirmuser/:id" => "superbowl#confirmuser"
  match "/confirm/:token/activation" => "home#activate"

  get "user_controller/new"

  get "sessions/new"

  root :to => "home#index"
  match "/login" => "home#login"
  match "/sessions/new" => "home#login"
  match "/forgot_password" => "password_resets#new"
  match "/signup" => "user#new"

  mount CommunityEngine::Engine => "/"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < BaseController
layout :resolve_layout
  before_filter :require_no_user
  before_filter :load_user_using_perishable_token, :only => [ :edit, :update ]


  uses_tiny_mce do
    {:only => [:show], :options => configatron.default_mce_options}
  end    

  def index
  	      render :action => :new
  end
  def new
  end

  def edit
  end

  def create
  	@user = User.find_by_email(params[:email])
    if @user
      @user.deliver_password_reset_instructions!

      flash[:info] = :your_password_reset_instructions_have_been_emailed_to_you.l      

      redirect_to login_path
    else
      flash[:info] = :sorry_we_dont_recognize_that_email_address.l      

      render :action => :new
    end

  end

  def show
  	  	      render :action => :edit
  end

  def update
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if @user.save
      flash[:notice] = :your_changes_were_saved.l

      redirect_to dashboard_user_path(@user)
    else
      flash[:info] = @user.errors.full_messages.to_sentence
      render :action => :edit
    end
  end





private 
def resolve_layout
    "unauth"
end

def load_user_using_perishable_token
    @user = User.find_using_perishable_token(params[:id])
    unless @user
      flash[:error] = :an_error_occurred.l
      redirect_to login_path
    end
end

end

app/views/password_resets/edit.html.haml
%style{:type => "text/css"}
  html,body{background-color: #eee;}
  body {padding-top: 0px;}
  == .formrails{margin:auto;}
  == .formrails .container{width:400px;}
  == .container > .content {background-color: #fff;padding: 20px;margin: 0 -20px;-webkit-border-radius: 10px 10px 10px 10px;-moz-border-radius: 10px 10px 10px 10px;border-radius: 10px 10px 10px 10px;-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);-moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);box-shadow: 0 1px 2px rgba(0,0,0,.15);}
  == .login-form {margin-left: 65px;} 
  legend{margin-right: -50px;font-weight: bold;color: #404040;}

%section{:id=>"features"}
  %div{:id=>"features-banner", "data-stellar-background-ratio"=>"0"}
    %div{:class=>"formrails"}
      %div{:class=>"container"}
        %div{:class=>"content"}
          %div{:class=>"row"}
            %div{:class=>"login-form"}
              %h2= :forgot_your_password.l
              %hr
              = form_tag password_reset_path, :method => :put do
                = render :partial => "shared/messages"
                %fieldset
                  %div{:class=>"clearfix"}
                    = password_field_tag :password, nil, :size => 35, :placeholder=> :password.l
                  %div{:class=>"clearfix"}
                    = password_field_tag :password_confirmation, nil, :size => 35, :placeholder=> :confirm_password.l

                  = submit_tag :reset_my_password.l , :class=>"btn primary"            

app/views/password_resets/new.html.haml
%style{:type => "text/css"}
  html,body{background-color: #eee;}
  body {padding-top: 0px;}
  == .formrails{margin:auto;}
  == .formrails .container{width:400px;}
  == .container > .content {background-color: #fff;padding: 20px;margin: 0 -20px;-webkit-border-radius: 10px 10px 10px 10px;-moz-border-radius: 10px 10px 10px 10px;border-radius: 10px 10px 10px 10px;-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);-moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);box-shadow: 0 1px 2px rgba(0,0,0,.15);}
  == .login-form {margin-left: 65px;} 
  legend{margin-right: -50px;font-weight: bold;color: #404040;}

%section{:id=>"features"}
  %div{:id=>"features-banner", "data-stellar-background-ratio"=>"0"}
    %div{:class=>"formrails"}
      %div{:class=>"container"}
        %div{:class=>"content"}
          %div{:class=>"row"}
            %div{:class=>"login-form"}
              %h2 Reset Your Password
              %hr
              = form_tag password_resets_path do
                = render :partial => "shared/messages"
                %fieldset
                  %div{:class=>"clearfix"}
                    = text_field_tag 'email', nil, :size => 35, :placeholder=> 'Enter Your Email Address'
                  = submit_tag "Reset Password", :class=>"btn primary"            