config/routes.rb
Asto::Application.routes.draw do

  get "users/signup_completed"

  get "superbowl/confirm"
  get "superbowl/home"
  match "/approve/:id" => "superbowl#approve"
  match "/disapprove/:id" => "superbowl#disapprove"
  match "/confirmuser/:id" => "superbowl#confirmuser"
  match "/confirm/:token/activation" => "home#activate"

  get "user_controller/new"

  get "sessions/new"

  root :to => "home#index"
  match "/login" => "home#login"
  match "/sessions/new" => "home#login"
  match "/forgot_password" => "password_resets#new"
  match "/signup" => "user#new"

  mount CommunityEngine::Engine => "/"

end

app/models/user.rb
class User < ActiveRecord::Base
	require_from_ce('models/user')
	attr_accessible :coyemail, :coyname, :fname, :lname, :mobile,:position, :mname

protected

	def password_required?
    end
end

app/controllers/user_controller.rb
class UserController < BaseController
	layout :resolve_layout

  uses_tiny_mce do
    {:only => [:show], :options => configatron.default_mce_options}
  end    
  def new
  	@user         = User.new( {:birthday => Date.parse((Time.now - 25.years).to_s) }.merge(params[:user] || {}) )
    @inviter_id   = params[:id]
    @inviter_code = params[:code]
  end


private 
def resolve_layout
    "unauth"
end
end

app/controllers/users_controller.rb
class UsersController < BaseController
		layout :resolve_layout

  uses_tiny_mce do
        {:only => [:show], :options => configatron.default_mce_options}
  end 
  include Viewable
  cache_sweeper :taggable_sweeper, :only => [:activate, :update, :destroy]

  uses_tiny_mce do
    {:only => [:new, :create, :update, :edit, :welcome_about], :options => configatron.default_mce_options}
  end

  uses_tiny_mce do
    {:only => [:show], :options => configatron.simple_mce_options}
  end

  # Filters
  before_filter :login_required, :only => [:edit, :edit_account, :update, :welcome_photo, :welcome_about,
                                          :welcome_invite, :return_admin, :assume, :featured,
                                          :toggle_featured, :edit_pro_details, :update_pro_details, :dashboard, :deactivate,
                                          :crop_profile_photo, :upload_profile_photo]
  before_filter :find_user, :only => [:edit, :edit_pro_details, :show, :update, :destroy, :statistics, :deactivate,
                                      :crop_profile_photo, :upload_profile_photo ]
  before_filter :require_current_user, :only => [:edit, :update, :update_account,
                                                :edit_pro_details, :update_pro_details,
                                                :welcome_photo, :welcome_about, :welcome_invite, :deactivate,
                                                :crop_profile_photo, :upload_profile_photo]
  before_filter :admin_required, :only => [:assume, :destroy, :featured, :toggle_featured, :toggle_moderator]
  before_filter :admin_or_current_user_required, :only => [:statistics]

  def activate
    redirect_to signup_path and return if params[:id].blank?
    @user = User.find_by_activation_code(params[:id])
    if @user and @user.activate
      self.current_user = @user
      @user.track_activity(:joined_the_site)
      flash[:notice] = :thanks_for_activating_your_account.l
      redirect_to welcome_photo_user_path(@user) and return
    end

    flash[:error] = :account_activation_error.l_with_args(:email => configatron.support_email)
    redirect_to signup_path
  end

  def deactivate
    @user.deactivate
    current_user_session.destroy if current_user_session
    flash[:notice] = :deactivate_completed.l
    redirect_to login_path
  end

  def index
    @users, @search, @metro_areas, @states = User.search_conditions_with_metros_and_states(params)

    @users = @users.active.recent.includes(:tags).page(params[:page]).per(20)

    @metro_areas, @states = User.find_country_and_state_from_search_params(params)

    @tags = User.tag_counts :limit => 10

    setup_metro_areas_for_cloud
  end

  def dashboard
    @user = current_user
    @network_activity = @user.network_activity
    @recommended_posts = @user.recommended_posts
  end

  def show
    @friend_count               = @user.accepted_friendships.count
    @accepted_friendships       = @user.accepted_friendships.find(:all, :limit => 5).collect{|f| f.friend }
    @pending_friendships_count  = @user.pending_friendships.count()

    @comments       = @user.comments.find(:all, :limit => 10, :order => 'created_at DESC')
    @photo_comments = Comment.find_photo_comments_for(@user)
    @users_comments = Comment.find_comments_by_user(@user).limit(5)

    @recent_posts   = @user.posts.recent.find(:all, :limit => 2)
    @clippings      = @user.clippings.find(:all, :limit => 5)
    @photos         = @user.photos.find(:all, :limit => 5)
    @comment        = Comment.new(params[:comment])

    @my_activity = Activity.recent.by_users([@user.id]).find(:all, :limit => 10)

    update_view_count(@user) unless current_user && current_user.eql?(@user)
  end

  def new
    @user         = User.new( {:birthday => Date.parse((Time.now - 25.years).to_s) }.merge(params[:user] || {}) )
    @inviter_id   = params[:id]
    @inviter_code = params[:code]
  end

  def create
    @user       = User.new(params[:user])
    @user.role  = Role[:member]

    if (!configatron.require_captcha_on_signup || verify_recaptcha(@user)) && @user.save
      create_friendship_with_inviter(@user, params)
      flash[:notice] = :email_signup_thanks.l_with_args(:email => @user.email)
      redirect_to signup_completed_user_path(@user)
    else
      render :action => 'new'
    end
  end

  def edit
    @metro_areas, @states = setup_locations_for(@user)
    @avatar     = (@user.avatar || @user.build_avatar)
  end

  def update
    @metro_areas, @states = setup_locations_for(@user)

    unless params[:metro_area_id].blank?
      @user.metro_area  = MetroArea.find(params[:metro_area_id])
      @user.state       = (@user.metro_area && @user.metro_area.state) ? @user.metro_area.state : nil
      @user.country     = @user.metro_area.country if (@user.metro_area && @user.metro_area.country)
    else
      @user.metro_area = @user.state = @user.country = nil
    end

    @user.tag_list = params[:tag_list] || ''

    params[:user][:avatar_attributes].merge!(:user_id => @user.id) if params[:user] && params[:user][:avatar_attributes]

    if @user.update_attributes(params[:user])
      @user.track_activity(:updated_profile)

      flash[:notice] = :your_changes_were_saved.l
      unless params[:welcome]
        redirect_to user_path(@user)
      else
        redirect_to :action => "welcome_#{params[:welcome]}", :id => @user
      end
    else
      render :action => 'edit'
    end
  end

  def destroy
    unless @user.admin? || @user.featured_writer?
      @user.destroy
      flash[:notice] = :the_user_was_deleted.l
    else
      flash[:error] = :you_cant_delete_that_user.l
    end
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  def change_profile_photo
    @user   = User.find(params[:id])
    @photo  = Photo.find(params[:photo_id])
    @user.avatar = @photo

    if @user.save!
      flash[:notice] = :your_changes_were_saved.l
      redirect_to user_photo_path(@user, @photo)
    end
  rescue ActiveRecord::RecordInvalid
    @metro_areas, @states = setup_locations_for(@user)
    render :action => 'edit'
  end

  def crop_profile_photo
    unless @photo = @user.avatar
      flash[:notice] = :no_profile_photo.l
      redirect_to upload_profile_photo_user_path(@user) and return
    end
    return unless request.put?

    @photo.update_attributes(:crop_x => params[:crop_x], :crop_y => params[:crop_y], :crop_w => params[:crop_w], :crop_h => params[:crop_h])
    redirect_to user_path(@user)
  end

  def upload_profile_photo
    @avatar       = Photo.new(params[:avatar])
    return unless request.put?

    @avatar.user  = @user
    if @avatar.save
      @user.avatar  = @avatar
      @user.save
      redirect_to crop_profile_photo_user_path(@user)
    end
  end

  def edit_account
    @user             = current_user
    @authorizations   = current_user.authorizations
    @is_current_user  = true
  end

  def update_account
    @user             = current_user

    if @user.update_attributes(params[:user])
      flash[:notice] = :your_changes_were_saved.l
      respond_to do |format|
        format.html {redirect_to user_path(@user)}
        format.js
      end
    else
      respond_to do |format|
        format.html {render :action => 'edit_account'}
        format.js
      end
    end
  end

  def edit_pro_details
    @user = User.find(params[:id])
  end

  def update_pro_details
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      respond_to do |format|
        format.html {
          flash[:notice] = :your_changes_were_saved.l
          redirect_to edit_pro_details_user_path(@user)
        }
        format.js {
          render :text => 'success'
        }
      end

    end
  rescue ActiveRecord::RecordInvalid
    render :action => 'edit_pro_details'
  end

  def create_friendship_with_inviter(user, options = {})
    unless options[:inviter_code].blank? or options[:inviter_id].blank?
      friend = User.find(options[:inviter_id])

      if friend && friend.valid_invite_code?(options[:inviter_code])
        accepted    = FriendshipStatus[:accepted]
        @friendship = Friendship.new(:user_id => friend.id,
          :friend_id => user.id,
          :friendship_status => accepted,
          :initiator => true)

        reverse_friendship = Friendship.new(:user_id => user.id,
          :friend_id => friend.id,
          :friendship_status => accepted )

        @friendship.save!
        reverse_friendship.save!
      end
    end
  end

  def signup_completed
    @user = User.find(params[:id])
    redirect_to home_path and return unless @user
  end

  def welcome_photo
    @user = User.find(params[:id])
    @avatar = (@user.avatar || @user.build_avatar)
  end

  def welcome_about
    @user = User.find(params[:id])
    @metro_areas, @states = setup_locations_for(@user)
  end

  def welcome_invite
    @user = User.find(params[:id])
  end

  def invite
    @user = User.find(params[:id])
  end

  def welcome_complete
    flash[:notice] = :walkthrough_complete.l_with_args(:site => configatron.community_name)
    redirect_to user_path
  end

  def forgot_username
    return unless request.post?

    if @user = User.active.find_by_email(params[:email])
      UserNotifier.forgot_username(@user).deliver
      redirect_to login_url
      flash[:info] = :your_username_was_emailed_to_you.l
    else
      flash[:error] = :sorry_we_dont_recognize_that_email_address.l
    end
  end

  def resend_activation

    if params[:email]
      @user = User.find_by_email(params[:email])
    else
      @user = User.find(params[:id])
    end

    if @user && !@user.active?
      flash[:notice] = :activation_email_resent_message.l
      UserNotifier.signup_notification(@user).deliver
      redirect_to login_path and return
    else
      flash[:notice] = :activation_email_not_sent_message.l
    end
  end

  def assume
    user = User.find(params[:id])

    if assumed_user_session = self.assume_user(user)

app/views/users/new.html.haml
%style{:type => "text/css"}
  html,body{background-color: #eee;}
  body {padding-top: 0px;}
  == .formrails{margin:auto;width:900px;}
  == .formrails .container{width:900px;}
  == .container > .content {background-color: #fff;padding: 20px;margin: 0 -20px;-webkit-border-radius: 10px 10px 10px 10px;-moz-border-radius: 10px 10px 10px 10px;border-radius: 10px 10px 10px 10px;-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);-moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);box-shadow: 0 1px 2px rgba(0,0,0,.15);}
  == .login-form {margin-left: 65px;} 
  legend{margin-right: -50px;font-weight: bold;color: #404040;}
  == .lightblue {background-color: none;}

%section{:id=>"features"}
  %div{:id=>"features-banner","data-stellar-background-ratio"=>"0"}
    %div{:class=>"formrails"}
      %div{:class=>"container"}
        %div{:class=>"content"}
          %div{:class=>"row"}
            %div{:class=>"login-form"}
              %h2 Sign Up: Get Involved
              %hr
              = error_messages_for :user
              = form_for :user, :url => users_path do |f|
                %div{:class=>"row-fluid"}
                  %div{:class=>"span12 bgcolor"}
                    %label Personal Details
                %div{:class=>"row-fluid"}
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :fname, :placeholder=>"First Name", :class=>"span12 input-mini"
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :lname, :placeholder=>"Last Name", :class=>"span12 input-mini" 
                %div{:class=>"row-fluid"}
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :mname, :placeholder=>"Middle Name", :class=>"span12 input-mini"
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :mobile, :placeholder=>"Mobile", :class=>"span12 input-mini"    
                %div{:class=>"row-fluid"}
                  %div{:class=>"span12 bgcolor"}
                    %label{"for"=>"user_birthdate"}
                      =:birthday.l
                    = date_select :user, :birthday,{:start_year => (Time.now.year - configatron.max_age), :end_year => (Time.now.year - configatron.min_age)}

                %div{:class=>"row-fluid"}
                  %div{:class=>"span12 bgcolor"}
                    %label Business Details
                    = f.text_field :coyname, :placeholder=>"Company Name", :class=>"span12 input-mini"
                %div{:class=>"row-fluid"}
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :position, :placeholder=>"Position", :class=>"span12 input-mini"
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :coyemail, :placeholder=>"Company Email", :class=>"span12 input-mini"
                %div{:class=>"row-fluid"}
                  %div{:class=>"span12 bgcolor"}
                    %label Login Details
                %div{:class=>"row-fluid"}
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :login, :placeholder=>"Username", :class=>"span12 input-mini"
                  %div{:class=>"span6 bgcolor"}
                    = f.text_field :email, :placeholder=>"Email Address", :class=>"span12 input-mini"  
                    = hidden_field_tag :inviter_id, params[:inviter_id]
                    = hidden_field_tag :inviter_code, params[:inviter_code]
                = submit_tag "Register for Astoria", :class=>"btn primary" 
              %div{:class=>"span4"}

app/views/users/signup_completed.html.erb
<h1>Users#signup_completed</h1>
<p>Find me in app/views/users/signup_completed.html.erb</p>

app/views/users/signup_completed.html.haml
%style{:type => "text/css"}
  html,body{background-color: #eee;}
  body {padding-top: 0px;}
  == .formrails{margin:auto;width:900px;}
  == .formrails .container{width:900px;}
  == .container > .content {background-color: #fff;padding: 20px;margin: 0 -20px;-webkit-border-radius: 10px 10px 10px 10px;-moz-border-radius: 10px 10px 10px 10px;border-radius: 10px 10px 10px 10px;-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);-moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);box-shadow: 0 1px 2px rgba(0,0,0,.15);}
  == .login-form {margin-left: 65px;} 
  legend{margin-right: -50px;font-weight: bold;color: #404040;}
  == .lightblue {background-color: none;}

%section{:id=>"features"}
  %div{:id=>"features-banner","data-stellar-background-ratio"=>"0"}
    %div{:class=>"formrails"}
      %div{:class=>"container"}
        %div{:class=>"content"}
          %div{:class=>"row"}
            %div{:class=>"login-form"}
              %h2 Thank You!
              %hr
              %h5 Go check your email
              %ul.list.checks
              %li Look for a message from: Astoria
              %li See you back here in a short while.
            %div{:class=>"span4"}



 