config/routes.rb
Asto::Application.routes.draw do

  get "users/signup_completed"

  get "superbowl/confirm"
  get "superbowl/home"
  match "/approve/:id" => "superbowl#approve"
  match "/disapprove/:id" => "superbowl#disapprove"
  match "/confirmuser/:id" => "superbowl#confirmuser"
  match "/confirm/:token/activation" => "home#activate"

  get "user_controller/new"

  get "sessions/new"

  root :to => "home#index"
  match "/login" => "home#login"
  match "/sessions/new" => "home#login"
  match "/forgot_password" => "password_resets#new"
  match "/signup" => "user#new"

  mount CommunityEngine::Engine => "/"

end

app/controllers/home_controller.rb
class HomeController < BaseController
	layout :resolve_layout

      uses_tiny_mce do
            {:only => [:show], :options => configatron.default_mce_options}
       end    
      
  def index
  end

  def login
  	   redirect_to user_path(current_user) and return if current_user
        @user_session = UserSession.new
  end

  def activate
      @token = [params[:token]]
      ifexist = User.find_by_activation_token(@token)
      if ifexist
      @user = ifexist
      if request.post?
        password = params[:password]
        password_confirmation = params[:password_confirmation]
        if password != password_confirmation
          flash[:notice] = "***** password doesn't match confirmation"
          flash[:color] = "invalid"
        else
         # @user.updating_password = true
          @user.password = password
          @user.activation_token = nil
          if @user.save
            UserMailer.successful_registration(@user).deliver
            redirect_to root_url, :notice => "Account Activated! You can now login"
          #redirect_to profile_path(@get_user.username)
          else
            logger.info('hashed password 2: '+ @user.password)
            flash[:alert] = 'Your password could not be changed. Please try again'
          end    
        end
      end
  else
    flash[:notice] = "Invalid token"
    redirect_to :action=>"index"
  end
    
  end


  private 
def resolve_layout
    "unauth"
end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activate.html.haml
%style{:type => "text/css"}
  html,body{background-color: #eee;}
  body {padding-top: 0px;}
  == .formrails{margin:auto;}
  == .formrails .container{width:400px;}
  == .container > .content {background-color: #fff;padding: 20px;margin: 0 -20px;-webkit-border-radius: 10px 10px 10px 10px;-moz-border-radius: 10px 10px 10px 10px;border-radius: 10px 10px 10px 10px;-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);-moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);box-shadow: 0 1px 2px rgba(0,0,0,.15);}
  == .login-form {margin-left: 65px;} 
  legend{margin-right: -50px;font-weight: bold;color: #404040;}
  == .lightblue {background-color: none;}

%section{:id=>"features"}
  %div{:id=>"features-banner","data-stellar-background-ratio"=>"0"}
    %div{:class=>"formrails"}
      %div{:class=>"container"}
        %div{:class=>"content"}
          %div{:class=>"row"}
            %div{:class=>"login-form"}
              %h2 Set Your Password
              %hr
              = form_tag(:action => 'activate') do
                = render :partial => "shared/messages"
                %fieldset
                  %div{:class=>"clearfix"}
                    = password_field_tag :password, nil, :placeholder => 'New Password'
                  %div{:class=>"clearfix"}
                    = password_field_tag :password_confirmation, nil, :placeholder=> 'Confirm Password'
                  %p
                  = submit_tag :reset_my_password.l, :class=>"btn primary" 

app/views/home/login.html.haml
%style{:type => "text/css"}
  html,body{background-color: #eee;}
  body {padding-top: 0px;}
  == .formrails{margin:auto;}
  == .formrails .container{width:400px;}
  == .container > .content {background-color: #fff;padding: 20px;margin: 0 -20px;-webkit-border-radius: 10px 10px 10px 10px;-moz-border-radius: 10px 10px 10px 10px;border-radius: 10px 10px 10px 10px;-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);-moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);box-shadow: 0 1px 2px rgba(0,0,0,.15);}
  == .login-form {margin-left: 65px;} 
  legend{margin-right: -50px;font-weight: bold;color: #404040;}




%section{:id=>"features"}
  %div{:id=>"features-banner","data-stellar-background-ratio"=>"0"}
    %div{:class=>"formrails"}
      %div{:class=>"container"}
        %div{:class=>"content"}
          %div{:class=>"row"}
            %div{:class=>"login-form"}
              %h2 Astoria Login
              %hr
              = form_tag sessions_path  do
                = render :partial => "shared/messages"

                %fieldset
                  %div{:class=>"clearfix"}
                    = text_field_tag :email, nil, :placeholder => 'Email'
                  %div{:class=>"clearfix"}
                    = password_field_tag :password, nil, :placeholder=> 'Password'
                  %label{"for"=>"remember_me"}
                  =:remember_me.l
                  = check_box_tag 'remember_me'
                  %p
                  = submit_tag "Sign in" , :class=>"btn primary" 
          %div{:class=>"bottom-link-bar"}
            %div{:class=>"link-bar"}
              = link_to "Forgot your password?", "/forgot_password"
              %br
              = link_to "Didn't receive confirmation instructions?", "#"